### ISSUE TITLE
Find 3D kid(s) models

### ISSUE THREAD

**Issue by mostachostudios** [mostachostudios/TJ_game#1]
- low poly
- rigged ? can we use mixamo?
- fat/slim/...
- Teacher-like model too (same source if possible for style concordance)

(kenney)

**Comment by Leoniels** [comment]
https://assetstore.unity.com/packages/3d/characters/humanoids/sporty-girl-29666
This is at the moment the only asset that might fit our purposes in the Unity Asset Store but still, its just one character.
