### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Leoniels** [mostachostudios/TJ_game#25]
Camera that follows player.
·Take movement in mind #13

**Comment by Adrian-Dev** [comment]
Should we allow the user to pan the camera around the character by pressing the secondary mouse button, or simply make the camera stay fixed behind the character? Consider also if adding the feature "zooming in and out" is desirable (using mouse scroll wheel)

**Comment by Adrian-Dev** [comment]
Also, in order to make dodge mechanic easier for the user experience, consider rotating main character around "Y axis" when moving the mouse, so this way we can use "A" and "D" keys to perform dodge action (similar to a FPS but in a third person view)
